### ISSUE TITLE
Separate package for interfaces?

### ISSUE THREAD

**Issue by codymullins** [devlooped/CloudActors#74]
Hey there, I'm trying to understand where this project fits.

I see the `Devlooped.CloudActors` package has a dependency on `Orleans.Server`, and this package includes the interfaces for `IActorCommand`, etc. 

How do you envision this being used? For example, do you foresee these actors only being for internal usage? Suppose a system (FOO) is built with these actors. The system has clients (BAR) that need to connect to it to perform operations. Would it be expected that something else sits in front of this, e.g. an API? Or could a nuget package be published that allows BAR to call FOO using the message bus?

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Hi there! 

I have a work in [progress branch](https://github.com/devlooped/CloudActors/compare/main...dev/server) that decouples the server from the main package for precisely this. The idea is that your business logic can be completely ignorant of Orleans, and you can simply use the message bus to invoke the logic from anywhere in the app.

Due to a [current limitation/bug in orleans](https://github.com/dotnet/orleans/pull/9104), I haven't been able to merge and ship that yet. I'm hoping that will be fixed eventually and I'll move forward with the split.

**Comment by samcov** [comment]
**Very good!!! Looking forward to that release!**

**Comment by kzu** [comment]
Please go upvote the [issue in Orleans](https://github.com/dotnet/orleans/issues/9092) so we can get more traction 🙏

**Comment by johnkattenhorn** [comment]
Done too!

**Comment by kzu** [comment]
The fix is now in, YAY!. So I'm just waiting for it to ship so I can move forward with this

**Comment by kzu** [comment]
Orleans just shipped v9 last week which now contains the required fix. So I can now move forward with the split :)
